#!/bin/bash

# A script that will ask for a number and print out a message depending on the value. 

read -p "Enter a number: " n
case $n in
    ???) 
        echo "Three characters";;
    2) 
        echo "Two";;
    [3-9]) 
        echo "Three to nine";;
    *.txt) 
        echo "Ends with .txt";;
    *) 
        echo "Other";;
esac
    