#!/bin/bash

# Welcome to your first Bash Script
var='Hello World!'
current_dir=$(pwd)

readonly color="blue"
color="red" #Cannot modify readonly variables

echo "${var} from $current_dir and your favourite color is $color"

# Single quotes potentially correspond to strings
echo '${var} from $current_dir and your favourite color is $color'
